### PR TITLE
K8s secret reconciler

### LINKED ISSUE #65: API key secrets reconciliation
**Describe the bug**
Authorino currently doesn't acknowledge changes made to k8s secrets that represent API keys after the service is deployed, meaning any new secret, secret update or secret deletion will not be reflected in Authorino's internal cache of API keys until the `config.authorino.3scale.net/Service` 

**Help us Reproduce it**

1. Create a k8s secret that can work as an API key (i.e. opaque, containing an "api_key" key and label selectors)
2. Deploy a `config.authorino.3scale.net/Service` with API key auth enabled
3. Check that requests to the service using API key created in (1) works
4. Delete the k8s secret created in (1) – i.e. mimicking revocation
5. Check again requests to the service using API key created in (1) and see that it still works (i.e. revocation not acknowledged by Authorino)

**Expected behaviour**

Changes to matched k8s secrets reflected in Authorino – i.e.
- adding a new secret with an "api_key" key and matching label selectors creates a new credential to access the service
- deleting a secret revokes access to the service
- - updating an existing secret revokes previous corresponding API key and creates a new one

**Environment (please complete the following information):**
All environments

**Solution proposal**
A second reconciler, only for secrets, could be introduced. This second reconciler should trigger an update on the main reconciler whenever it acknowledges changes to the watched secrets.

To solve the problem of matching the right secrets to watch independently of reconciliating service configs first, a new Authorino-specific label could be defined and required to be added to every secret.

### PR DESCRIPTION
**Pull request by guicassolato**
Closes #65

----

Introduces the requirement for k8s secrets meant for being used as API keys to always include a label `authorino.3scale.net/managed-by` (with whatever non-null value). Consequently, all services configured for API key authentication must as well include in its `label_selectors` of the `api_key` identity config this new label `authorino.3scale.net/managed-by` (with value matching the one used in the secrets).

A limitation of the implementation here presented is that deleted secrets trigger the reconciler but cannot be checked for matching labels and corresponding affected services. This makes a bit harder for the revoking of access to services by deleting the secrets. Two possible workarounds to this limitation are:
- i) first update the secret before deleting it (i.e. remove the `api_key` entry or change its value)
- ii) enhance with authorization policies that check attributes of the resolved secret (e.g. use the secret's `creationTimestamp` for short-lived API keys working as access tokens)

### CODE REVIEW

File: controllers/secret_controller_test.go [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+func (r *FakeReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
+	r.Reconciled = true
+	return ctrl.Result{}, nil
+}
+
+func (r *FakeReconciler) Reset() {
+	r.Reconciled = false
+}
+
+func TestReconciler(t *testing.T) {
```
Comment (didierofrivia) [inline controllers/secret_controller_test.go:31]: Maybe we could do the creation of Service and Secrets outside the `TestReconciler` func, and separate the assertions addressing the type of secrets and if the service was reconciled or not? That way it would be easier to debug and to keep track of coverage

File: examples/echo-api-key-simple.yaml [hunk 2]
```diff
@@ -12,12 +12,18 @@ spec:
...
+        uuid: e314f9a7-3381-4fe9-bc74-4bc02c7a666f
+        inlineRego: |
+          allow {
+            creationTimestampStr := object.get(object.get(identity, "metadata", {}), "creationTimestamp", {})
+            creationTimestamp := time.parse_rfc3339_ns(creationTimestampStr)
+            durationNs := time.now_ns() - creationTimestamp
+            durationSec := durationNs/1000000000
+            durationMin := durationSec/60
+            durationMin < 5
+          }
```
Comment (didierofrivia) [inline examples/echo-api-key-simple.yaml:29]: As we discussed previously, maybe it would be better to extract this rego expiring key policy to a different file, and leave this one simpler with the non expiring key?

File: controllers/secret_controller_test.go (hunk 1 above)
Comment (guicassolato) [reply controllers/secret_controller_test.go]: I ended up creating a `<Subject>Test` struct. Our former approach of declaring variables that are reused across multiple tests in the same test file easily run into naming conflicts with other files of the same package.

File: controllers/secret_controller_test.go [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+func (r *FakeReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
+	r.Reconciled = true
+	return ctrl.Result{}, nil
+}
+
+func (r *FakeReconciler) Reset() {
+	r.Reconciled = false
+}
+
+type SecretReconcilerTest struct {
```
Comment (didierofrivia) [inline controllers/secret_controller_test.go:32]: maybe no need to export this, since it's quite specific to these batch of tests.

```suggestion
type secretReconcilerTest struct {
```

**Review by didierofrivia — APPROVED** [review]
